# renew_before_expiry = 30 days
version = 2.11.0
archive_dir = /etc/letsencrypt/archive/datacube.uxlivinglab.online
cert = /etc/letsencrypt/live/datacube.uxlivinglab.online/cert.pem
privkey = /etc/letsencrypt/live/datacube.uxlivinglab.online/privkey.pem
chain = /etc/letsencrypt/live/datacube.uxlivinglab.online/chain.pem
fullchain = /etc/letsencrypt/live/datacube.uxlivinglab.online/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 73c1928855bc21bc49100ba11cae001b
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
datacube.uxlivinglab.online = /var/www/certbot
